version: '3'
services:
  app:
    image: react-app
    container_name: react_app
    working_dir: /app
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"
